filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
build:
  environment:
          php:
              version: 8.2.6     # Do not use 2 digits, like 8.2. You need 3 digits like 8.2.6, without that xdebug won't be installed and test coverage will fail

  tests:
          override:
              -
                  command: 'php -n -dzend_extension=xdebug -dxdebug.mode=coverage vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                  coverage:
                      file: 'build/logs/clover.xml'
                      format: 'clover'