filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
build:
  environment:
          php:
              version: 7.0      # Common versions: 5.4, 5.5, 5.6, 7.0 or hhvm