language: php
php:
#  - '5.4'
#  - '5.5'
#  - '5.6'
  - '7.0'
#  - '7.1'
#  - hhvm
#  - nightly
before_script:
  - composer install
script:
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/test-reporter --stdout > codeclimate.json
  - curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports